//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFSklep.WCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Products_TEST", Namespace="http://schemas.datacontract.org/2004/07/ProduktyService")]
    [System.SerializableAttribute()]
    public partial class Products_TEST : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ManIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProdIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpecificationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SubIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ManID {
            get {
                return this.ManIDField;
            }
            set {
                if ((this.ManIDField.Equals(value) != true)) {
                    this.ManIDField = value;
                    this.RaisePropertyChanged("ManID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProdID {
            get {
                return this.ProdIDField;
            }
            set {
                if ((this.ProdIDField.Equals(value) != true)) {
                    this.ProdIDField = value;
                    this.RaisePropertyChanged("ProdID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Specification {
            get {
                return this.SpecificationField;
            }
            set {
                if ((object.ReferenceEquals(this.SpecificationField, value) != true)) {
                    this.SpecificationField = value;
                    this.RaisePropertyChanged("Specification");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SubID {
            get {
                return this.SubIDField;
            }
            set {
                if ((this.SubIDField.Equals(value) != true)) {
                    this.SubIDField = value;
                    this.RaisePropertyChanged("SubID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Manufacturers", Namespace="http://schemas.datacontract.org/2004/07/ProduktyService")]
    [System.SerializableAttribute()]
    public partial class Manufacturers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Manufacturer_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Manufacturer_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFSklep.WCF.Products_TEST[] Products_TESTField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Manufacturer_Id {
            get {
                return this.Manufacturer_IdField;
            }
            set {
                if ((this.Manufacturer_IdField.Equals(value) != true)) {
                    this.Manufacturer_IdField = value;
                    this.RaisePropertyChanged("Manufacturer_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manufacturer_Name {
            get {
                return this.Manufacturer_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Manufacturer_NameField, value) != true)) {
                    this.Manufacturer_NameField = value;
                    this.RaisePropertyChanged("Manufacturer_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFSklep.WCF.Products_TEST[] Products_TEST {
            get {
                return this.Products_TESTField;
            }
            set {
                if ((object.ReferenceEquals(this.Products_TESTField, value) != true)) {
                    this.Products_TESTField = value;
                    this.RaisePropertyChanged("Products_TEST");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubCategory", Namespace="http://schemas.datacontract.org/2004/07/ProduktyService")]
    [System.SerializableAttribute()]
    public partial class SubCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFSklep.WCF.Category CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFSklep.WCF.Products_TEST[] Products_TESTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Subcategory_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subcategory_nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFSklep.WCF.Category Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_Id {
            get {
                return this.Category_IdField;
            }
            set {
                if ((this.Category_IdField.Equals(value) != true)) {
                    this.Category_IdField = value;
                    this.RaisePropertyChanged("Category_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFSklep.WCF.Products_TEST[] Products_TEST {
            get {
                return this.Products_TESTField;
            }
            set {
                if ((object.ReferenceEquals(this.Products_TESTField, value) != true)) {
                    this.Products_TESTField = value;
                    this.RaisePropertyChanged("Products_TEST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subcategory_id {
            get {
                return this.Subcategory_idField;
            }
            set {
                if ((this.Subcategory_idField.Equals(value) != true)) {
                    this.Subcategory_idField = value;
                    this.RaisePropertyChanged("Subcategory_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subcategory_name {
            get {
                return this.Subcategory_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Subcategory_nameField, value) != true)) {
                    this.Subcategory_nameField = value;
                    this.RaisePropertyChanged("Subcategory_name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/ProduktyService")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Category_IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Category_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WPFSklep.WCF.SubCategory[] SubCategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Category_Id {
            get {
                return this.Category_IdField;
            }
            set {
                if ((this.Category_IdField.Equals(value) != true)) {
                    this.Category_IdField = value;
                    this.RaisePropertyChanged("Category_Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Category_name {
            get {
                return this.Category_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.Category_nameField, value) != true)) {
                    this.Category_nameField = value;
                    this.RaisePropertyChanged("Category_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WPFSklep.WCF.SubCategory[] SubCategory {
            get {
                return this.SubCategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.SubCategoryField, value) != true)) {
                    this.SubCategoryField = value;
                    this.RaisePropertyChanged("SubCategory");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IProdukty")]
    public interface IProdukty {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetProdukty", ReplyAction="http://tempuri.org/IProdukty/GetProduktyResponse")]
        WPFSklep.WCF.Products_TEST[] GetProdukty();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetProdukty", ReplyAction="http://tempuri.org/IProdukty/GetProduktyResponse")]
        System.Threading.Tasks.Task<WPFSklep.WCF.Products_TEST[]> GetProduktyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetManufacturers", ReplyAction="http://tempuri.org/IProdukty/GetManufacturersResponse")]
        WPFSklep.WCF.Manufacturers[] GetManufacturers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetManufacturers", ReplyAction="http://tempuri.org/IProdukty/GetManufacturersResponse")]
        System.Threading.Tasks.Task<WPFSklep.WCF.Manufacturers[]> GetManufacturersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetSubcategory", ReplyAction="http://tempuri.org/IProdukty/GetSubcategoryResponse")]
        WPFSklep.WCF.SubCategory[] GetSubcategory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProdukty/GetSubcategory", ReplyAction="http://tempuri.org/IProdukty/GetSubcategoryResponse")]
        System.Threading.Tasks.Task<WPFSklep.WCF.SubCategory[]> GetSubcategoryAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProduktyChannel : WPFSklep.WCF.IProdukty, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProduktyClient : System.ServiceModel.ClientBase<WPFSklep.WCF.IProdukty>, WPFSklep.WCF.IProdukty {
        
        public ProduktyClient() {
        }
        
        public ProduktyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProduktyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduktyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProduktyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WPFSklep.WCF.Products_TEST[] GetProdukty() {
            return base.Channel.GetProdukty();
        }
        
        public System.Threading.Tasks.Task<WPFSklep.WCF.Products_TEST[]> GetProduktyAsync() {
            return base.Channel.GetProduktyAsync();
        }
        
        public WPFSklep.WCF.Manufacturers[] GetManufacturers() {
            return base.Channel.GetManufacturers();
        }
        
        public System.Threading.Tasks.Task<WPFSklep.WCF.Manufacturers[]> GetManufacturersAsync() {
            return base.Channel.GetManufacturersAsync();
        }
        
        public WPFSklep.WCF.SubCategory[] GetSubcategory() {
            return base.Channel.GetSubcategory();
        }
        
        public System.Threading.Tasks.Task<WPFSklep.WCF.SubCategory[]> GetSubcategoryAsync() {
            return base.Channel.GetSubcategoryAsync();
        }
    }
}
